name: Docker

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2.0.0

    - name: Login to GitHub Packages
      uses: docker/login-action@v2.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3.0.0
      with:
        context: docker
        push: true
        build-args: INCUBATOR_VER=${{ github.sha }}
        tags: ghcr.io/${{ github.repository }}/workspace:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
